### ISSUE TITLE
textlive安装

### ISSUE THREAD

**Issue by Purpleashes** [OpenHUTB/bazaar#21]
怎么确实自己的textlive安装好了，本地右击好像不能同步git。

**Comment by donghaiwang** [comment]
textlive只是编译.tex文件的，texstudio是.tex的编辑器；
Git安装后，再安装TortoiseGit后才能在鼠标右键看到git选项。

texlive安装后再安装目录中会看到这些文件：
![image](https://user-images.githubusercontent.com/7724320/225846729-83a60123-ccd9-4dac-b9aa-cb56c5547a9d.png)
