### ISSUE TITLE
请大神帮我们梳理一下流程

### ISSUE THREAD

**Issue by Sandra2Ha** [OpenHUTB/bazaar#23]

**Comment by AwooDancer** [comment]
我更新了readme，等老师同意pr就可以看到了。

**Comment by donghaiwang** [comment]
可以了，在readme.md中的“开源项目管理”中。

**Comment by donghaiwang** [comment]
![image](https://user-images.githubusercontent.com/7724320/227121799-554e0aac-cf76-4680-b281-8380ecc3ad9f.png)

![image](https://user-images.githubusercontent.com/7724320/227121879-3b7cb8ba-71f9-4e4c-bb7b-7a0d6dc96668.png)

**Comment by donghaiwang** [comment]
[为 Github 开源项目贡献代码](https://github.com/shaodahong/dahong/issues/20)

**Comment by Sandra2Ha** [comment]
> 我更新了readme，等老师同意pr就可以看到了。
