### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by Duan359** [OpenHUTB/bazaar#25]
![d3b4cbe073965f17d7b4db797a07687](https://user-images.githubusercontent.com/124792217/227089103-cba010c7-36cc-4ae8-802c-9e148d92f6d7.png)

**Comment by donghaiwang** [comment]
这种问题比较常见，可以先搜索下解决方案，多试试，比如：https://blog.csdn.net/HZC0217/article/details/121876026

**Comment by donghaiwang** [comment]
如果问题解决，请主动关闭Issues
