### ISSUE TITLE
推送报错

### ISSUE THREAD

**Issue by superzeroT** [OpenHUTB/bazaar#33]
![push](https://user-images.githubusercontent.com/50793022/227461904-e7b9f234-0321-4dc6-9059-320ddc777194.png)

**Comment by donghaiwang** [comment]
多推送几次，或者参考 #31

**Comment by jianiwuoo** [comment]
我也经常遇到这种问题，可以尝试关闭后，通过“同步”按钮中的“推送”再进行一次推送，这种情况下我是可以成功推送的，你尝试一下。
![1680273477694](https://user-images.githubusercontent.com/127365229/229151549-3583373e-e76f-41b5-a76a-8b95a4baf156.png)

**Comment by donghaiwang** [comment]
如果没问题，请主动关闭Issues

**Comment by superzeroT** [comment]
好的
