### ISSUE TITLE
提交时提示：此提交不属于此存储库上的任何分支，可能属于存储库外部的分支。

### ISSUE THREAD

**Issue by cwycwy299** [OpenHUTB/bazaar#44]
第一次提交成功并上传成功，但是无法在github上拉取请求，提示此提交不属于此存储库上的任何分支，可能属于存储库外部的分支。
![I4JJ72@M2GOXE3ALXD5U(7](https://user-images.githubusercontent.com/127363284/228212105-bb2acc20-43ca-42c1-8104-c52a532d10c3.png)
在本地重新尝试上传，出现如下错误提醒：
![4AG3LYIVSZ7%DYNL63A1 EI_tmb](https://user-images.githubusercontent.com/127363284/228212221-be6530cb-8ba1-4c9c-a5fc-a472c3709f17.png)

**Comment by donghaiwang** [comment]
Updates were rejected because the tip of your current branch is behind
远程的代码已经更新，需要用git pull 重新同步下代码
