### ISSUE TITLE
克隆步骤问题

### ISSUE THREAD

**Issue by jianiwuoo** [OpenHUTB/bazaar#45]
使用Tortoisegit克隆时，填写的URL是自己fork之后仓库的，还是原仓库的呢？

**Comment by jianiwuoo** [comment]
![1680052874304](https://user-images.githubusercontent.com/127365229/228402142-35a45d97-44a2-4fbf-83d7-135039b2a78a.png)

**Comment by AwooDancer** [comment]
填写自己fork之后的仓库的url，同时你进行的pull、commit以及push操作都是在这个库里进行的。如果远端仓库更新了，可点击如图所示按钮进行同步，并用Tortoisegit或者git命令拉取。
![图片](https://user-images.githubusercontent.com/46441771/228402324-20672e6d-b279-473c-9c2d-87ea705cc2c4.png)

**Comment by jianiwuoo** [comment]
感谢！！
