### ISSUE TITLE
Texstudio构筑并查看时报错

### ISSUE THREAD

**Issue by wpr123** [OpenHUTB/bazaar#90]
把本地仓库删除后重新folk和克隆后依旧报错，未进行代码的修改，麻烦知道的人解答一下，谢谢！
![question](https://user-images.githubusercontent.com/71546572/231509795-26412378-b332-4dca-957b-68d24404e69a.png)

**Comment by Sandra2Ha** [comment]
本地文件夹和自己的仓库都删除了吗
